import CheckIcon from '@mui/icons-material/Check'
import CloseIcon from '@mui/icons-material/Close'
import {
  Box,
  FormControl,
  MenuItem,
  Paper,
  Select,
  Table,
  TableBody,
  TableContainer,
  TableHead,
  TableRow,
  TableSortLabel,
} from '@mui/material'
import { visuallyHidden } from '@mui/utils'
import { useEffect, useMemo, useState } from 'react'
import LabelMatchContainer from '../../../components/LabelMatchContainer'
import { StyledTableCell } from '../../../components/StyledComponent'
import useDataStore from '../../../store/DataStore'
import useMappingStore from '../../../store/MappingStore'
import { sortByKoreanStringDesc } from '../../../utils/Utils'

interface Column {
  id: 'base_column_name' | 'comparison_column_name' | 'status'
  label: string
  minWidth?: number
  align?: 'right'
  format?: (value: number) => string
}

const columns: readonly Column[] = [
  { id: 'base_column_name', label: '기준 파일 열', minWidth: 170 },
  { id: 'comparison_column_name', label: '비교 파일 열', minWidth: 100 },
  { id: 'status', label: '상태', minWidth: 100 },
]

const DataTable = () => {
  const {
    masterKeyColumnName,
    masterQuantityColumnName,
    fileConfigurations,
    step5ActiveColumn,
    step5ActiveFile,
    setStep5ValueMatchProgress,
    step5TemporaryEdits,
    setStep5TemporaryEdits,
  } = useMappingStore()

  const { parsedData, selectedDataId } = useDataStore()

  // 파일명으로 parsedData 에서 데이터 가져오기
  // 그 데이터에서 step5ActiveColumn 에 해당하는 컬럼의 고유 값 목록 가져오기
  const selectedFileUniqueColumnValues = useMemo(() => {
    if (!selectedDataId || !step5ActiveFile || !step5ActiveColumn) return []
    const uniqueValues = [
      ...new Set(
        parsedData
          .find(data => data.id === selectedDataId)
          ?.data.map(item => {
            const value = item[
              step5ActiveColumn.get(step5ActiveFile || '') || ''
            ] as string
            // ✅ 괄호 제거: '('부터 ')'까지 제거
            return value ? String(value).replace(/\([^)]*\)/g, '') : value
          })
          .filter(
            value => value !== null && value !== undefined && value !== '',
          ) || [],
      ),
    ]
    // 한글 내림차순 정렬
    return sortByKoreanStringDesc(uniqueValues)
  }, [parsedData, selectedDataId, step5ActiveColumn, step5ActiveFile])

  // 현재 활성화된 파일의 고유 값 목록 가져오기
  // 1. step5ActiveColumn에서 기준 파일의 컬럼명 가져오기
  // 2. fileConfigurations의 columnMappings에서 매핑된 비교 파일의 컬럼명 찾기
  // 3. 비교 파일 데이터에서 해당 컬럼의 고유 값 목록 추출
  const activeFileUniqueColumnValues = useMemo(() => {
    if (!step5ActiveFile || !step5ActiveColumn) return []

    // 기준 파일에서 선택된 컬럼명
    const selectedMasterColumn =
      step5ActiveColumn.get(step5ActiveFile || '') || ''

    // fileConfigurations에서 매핑된 컬럼명 찾기
    const fileConfig = fileConfigurations.get(step5ActiveFile || '')
    const mappedTargetColumn = fileConfig?.columnMappings[selectedMasterColumn]

    if (!mappedTargetColumn) return []

    // 비교 파일 데이터에서 매핑된 컬럼의 고유 값 추출 (빈 값 제외)
    const target = [
      ...new Set(
        parsedData
          .find(data => data.name === step5ActiveFile)
          ?.data.map(item => item[mappedTargetColumn] as string)
          .filter(
            value => value !== null && value !== undefined && value !== '',
          ) || [],
      ),
    ]

    // 한글 내림차순 정렬
    return sortByKoreanStringDesc(target)
  }, [parsedData, step5ActiveFile, step5ActiveColumn, fileConfigurations])

  // 행 자동 생성: 비교 파일의 고유 값 목록을 기반으로 자동 생성
  const initialRows = useMemo(() => {
    if (!step5ActiveFile || !step5ActiveColumn.get(step5ActiveFile)) {
      return []
    }

    // 비교 파일의 고유 값 목록 (좌측에 텍스트로 표시될 값들)
    const comparisonValues = activeFileUniqueColumnValues

    // step5TemporaryEdits에서 기존 선택값 가져오기 (영속성)
    const currentColumnName = step5ActiveColumn.get(step5ActiveFile) || ''
    const existingEdits = step5TemporaryEdits
      .get(step5ActiveFile)
      ?.get(currentColumnName)

    // 각 비교 값을 행으로 변환
    return comparisonValues.map(comparisonValue => {
      // 기존 선택값이 있으면 복원, 없으면 null
      const existingRow = existingEdits?.find(
        item => item.comparisonValue === comparisonValue,
      )

      // ✅ 저장된 값에서도 괄호 제거 (UI 옵션과 일치시키기 위해)
      let restoredMasterValue = existingRow?.masterValue || null
      if (restoredMasterValue && restoredMasterValue !== '__NONE__') {
        restoredMasterValue = restoredMasterValue.replace(/\([^)]*\)/g, '')
      }

      return {
        comparisonValue, // 좌측: 비교 파일 값 (텍스트)
        masterValue: restoredMasterValue, // 우측: 기존 값 복원 (괄호 제거됨)
      }
    })
  }, [
    step5ActiveFile,
    step5ActiveColumn,
    activeFileUniqueColumnValues,
    step5TemporaryEdits,
  ])

  // 로컬 상태로 관리 (사용자 선택값 저장)
  const [autoGeneratedRows, setAutoGeneratedRows] =
    useState<{ comparisonValue: string; masterValue: string | null }[]>(
      initialRows,
    )

  // initialRows가 변경되면 로컬 상태도 업데이트
  useEffect(() => {
    setAutoGeneratedRows(initialRows)
  }, [initialRows])

  // 정렬 상태 관리
  const [order, setOrder] = useState<'asc' | 'desc'>('asc')
  // 정렬 기준 관리
  const [orderBy, setOrderBy] = useState<string>('status')

  // 정렬 핸들러 생성
  const createSortHandler =
    (property: string) => (event: React.MouseEvent<unknown>) => {
      event.preventDefault()
      const isAsc = orderBy === property && order === 'asc'
      setOrder(isAsc ? 'desc' : 'asc')
      setOrderBy(property)
    }

  // 데이터 정렬 함수 (자동 생성된 행 기반)
  const getSortedData = () => {
    return [...autoGeneratedRows].sort((a, b) => {
      let compareResult = 0

      if (orderBy === 'status') {
        // 매칭 상태로 정렬 (masterValue가 있으면 매칭됨)
        const aMatched = !!a.masterValue
        const bMatched = !!b.masterValue

        compareResult = aMatched === bMatched ? 0 : aMatched ? -1 : 1
      }

      return order === 'asc' ? compareResult : -compareResult
    })
  }

  const sortedData = getSortedData()

  // 각 컬럼의 진행률은 선택된 항목 수 / 자동 생성된 행 수 * 100
  const columnProgress = useMemo(() => {
    if (!autoGeneratedRows.length) return 0

    return Math.round(
      (autoGeneratedRows.filter(
        item => item.masterValue !== null && item.masterValue !== '',
      ).length /
        autoGeneratedRows.length) *
        100,
    )
  }, [autoGeneratedRows])

  // 전체 진행률은 각 컬럼의 진행률 / 현재 화면에 노출된 컬럼 수
  const overallProgress = useMemo(() => {
    // 현재 화면에 노출된 컬럼 수
    const columnCount = Object.keys(
      fileConfigurations.get(step5ActiveFile || '')?.columnMappings || {},
    ).filter(
      column =>
        column !== masterKeyColumnName && column !== masterQuantityColumnName,
    ).length

    return Math.round(
      Array.from(
        fileConfigurations
          .get(step5ActiveFile || '')
          ?.valueMatchProgress?.progressByColumn?.values() || [],
      ).reduce((acc: number, curr: number) => acc + curr, 0) / columnCount,
    )
  }, [
    fileConfigurations,
    step5ActiveFile,
    masterKeyColumnName,
    masterQuantityColumnName,
  ])

  const checkIsMatched = (comparisonValue: string) => {
    const row = autoGeneratedRows.find(
      item => item.comparisonValue === comparisonValue,
    )
    return row?.masterValue !== null && row?.masterValue !== ''
  }

  useEffect(() => {
    if (!step5ActiveFile || !step5ActiveColumn.get(step5ActiveFile)) return

    setStep5ValueMatchProgress(
      step5ActiveFile,
      step5ActiveColumn.get(step5ActiveFile) || '',
      overallProgress,
      columnProgress,
    )
  }, [
    step5ActiveFile,
    step5ActiveColumn,
    overallProgress,
    columnProgress,
    setStep5ValueMatchProgress,
  ])

  return (
    <Box>
      <TableContainer
        sx={{ maxHeight: 440 }}
        component={Paper}
        elevation={0}
        variant="outlined"
      >
        <Table stickyHeader aria-label="sticky table">
          <TableHead>
            <TableRow>
              {columns.map(column => {
                return (
                  <StyledTableCell key={column.id} align={column.align}>
                    <TableSortLabel
                      key={column.id}
                      active={orderBy === column.id}
                      direction={orderBy === column.id ? order : 'asc'}
                      onClick={createSortHandler(column.id)}
                    >
                      {column.label}
                      {/* {column.label} */}
                      {orderBy === column.id ? (
                        <Box component="span" sx={visuallyHidden}>
                          {order === 'desc'
                            ? 'sorted descending'
                            : 'sorted ascending'}
                        </Box>
                      ) : null}
                    </TableSortLabel>
                    {/* {column.label} */}
                  </StyledTableCell>
                )
              })}
            </TableRow>
          </TableHead>
          {
            <TableBody>
              {sortedData.map((data, index) => (
                <TableRow
                  hover
                  key={`${step5ActiveFile || ''}-${data.comparisonValue}-${index}`}
                  tabIndex={-1}
                >
                  {/* 기준 파일 열 값 선택 (좌측) */}
                  <StyledTableCell>
                    <FormControl>
                      <Select
                        displayEmpty
                        size="small"
                        value={data.masterValue || ''}
                        inputProps={{ 'aria-label': 'Without label' }}
                        renderValue={selected => {
                          if (!selected) return '선택하세요'
                          if (selected === '__NONE__')
                            return '값 없음 (기준 파일에 없는 값)'
                          return selected
                        }}
                        onChange={e => {
                          const newMasterValue = e.target.value as string

                          // "값 없음" 선택 시 경고 메시지
                          if (newMasterValue === '__NONE__') {
                            const confirmMessage =
                              '⚠️ "값 없음"을 선택하면 이 값은 비교 시 기준 파일에 매칭되지 않습니다.\n\n' +
                              '계속하시겠습니까?'
                            if (!window.confirm(confirmMessage)) {
                              return // 취소 시 변경 안 함
                            }
                          }

                          // 1. 로컬 상태 업데이트
                          const updatedRows = autoGeneratedRows.map(row =>
                            row.comparisonValue === data.comparisonValue
                              ? {
                                  ...row,
                                  masterValue: newMasterValue || null,
                                }
                              : row,
                          )
                          setAutoGeneratedRows(updatedRows)

                          // 2. Store에 저장 (영속성)
                          if (
                            step5ActiveFile &&
                            step5ActiveColumn.get(step5ActiveFile)
                          ) {
                            const currentColumnName =
                              step5ActiveColumn.get(step5ActiveFile) || ''

                            // 기존 step5TemporaryEdits 복사
                            const updatedEdits = new Map(step5TemporaryEdits)

                            // 해당 파일의 Map 가져오기 (없으면 새로 생성)
                            const fileEdits =
                              updatedEdits.get(step5ActiveFile) || new Map()
                            const updatedFileEdits = new Map(fileEdits)

                            // 해당 컬럼에 updatedRows 저장
                            updatedFileEdits.set(currentColumnName, updatedRows)
                            updatedEdits.set(step5ActiveFile, updatedFileEdits)

                            // Store 업데이트
                            setStep5TemporaryEdits(updatedEdits)
                          }
                        }}
                      >
                        <MenuItem value="">선택하세요</MenuItem>
                        <MenuItem
                          value="__NONE__"
                          sx={{ color: '#999', fontStyle: 'italic' }}
                        >
                          값 없음 (기준 파일에 없는 값)
                        </MenuItem>
                        {selectedFileUniqueColumnValues.map(option => (
                          <MenuItem
                            key={`${data.comparisonValue}-${option}`}
                            value={option}
                          >
                            {option}
                          </MenuItem>
                        ))}
                      </Select>
                    </FormControl>
                  </StyledTableCell>
                  {/* 비교 파일 값 (텍스트, 읽기 전용, 우측) */}
                  <StyledTableCell>{data.comparisonValue}</StyledTableCell>
                  <StyledTableCell>
                    {checkIsMatched(data.comparisonValue) ? (
                      <LabelMatchContainer color="#E5F5E6">
                        <CheckIcon
                          sx={{ fontSize: '14px', color: '#2AA900' }}
                        />
                        매칭 완료
                      </LabelMatchContainer>
                    ) : (
                      <LabelMatchContainer color="#FFE5E5">
                        <CloseIcon
                          sx={{ fontSize: '14px', color: '#FF0004' }}
                        />
                        미매칭
                      </LabelMatchContainer>
                    )}
                  </StyledTableCell>
                </TableRow>
              ))}
            </TableBody>
          }
        </Table>
      </TableContainer>
    </Box>
  )
}

export default DataTable

// const StyledTableCell = styled(TableCell)(() => ({
//   [`&.${tableCellClasses.head}`]: {
//     backgroundColor: '#FAFAFA',
//     color: '#404040',
//     fontSize: 12,
//     fontWeight: 'bold',
//     height: '40px',
//     paddingBottom: '0',
//     paddingTop: '0',
//   },
//   [`&.${tableCellClasses.body}`]: {
//     fontSize: 14,
//   },
// }))
